&deploy_to: /var/www/websocket

pid: ! '%{deploy_to}/shared/pids/thin.pid'
timeout: 30
wait: 30
log: ! '%{deploy_to}/current/log/thin.log'
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
socket: ! '%{deploy_to}/shared/thin.sock'
chdir: ! '%{deploy_to}/current'
tag: websocket