pid: /var/www/websocket/shared/pids/thin.pid
port: 3000
timeout: 30
wait: 30
log: /var/www/websocket/current/log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1\2
threaded: true
no-epoll: true
daemonize: true
socket: /var/www/websocket/shared/thin.sock
chdir: /var/www/websocket/current
tag: websocket